name: 'Download MNIST GitHub Action'
description: 'http://yann.lecun.com/exdb/mnist Dataset Mirror'

inputs:
  target_dir:
    description: 'Target dir. Defaults: .'
    required: true
    default: '.'

runs:
  using: 'composite'
  steps:
    - run: mkdir -p ${{ inputs.target_dir }}/MNIST/raw
      shell: bash

    - run: cp ${{ github.action_path }}/*.gz ${{ inputs.target_dir }}/MNIST/raw
      shell: bash

    - run: ls -R ${{ inputs.target_dir }}/MNIST
      shell: bash
