name: 'Download MNIST GitHub Action'
description: 'http://yann.lecun.com/exdb/mnist Dataset Mirror'

inputs:
  target_dir:
    description: 'Target dir. Defaults: .'
    required: true
    default: '.'

runs:
  using: 'composite'
  steps:
    - run: echo "INPUT_TARGET_DIR=${{ inputs.target_dir }}" >> $GITHUB_ENV
      shell: bash
    - run: python3 -m venv action_env || python -m venv action_env || echo ""
      shell: bash
    - run: action_env/bin/python3 -m pip install torch==1.8.0 torchvision==0.9.0 -f https://download.pytorch.org/whl/cpu/torch_stable.html || action_env/Scripts/python.exe -m pip install torch==1.8.0 torchvision==0.9.0 -f https://download.pytorch.org/whl/cpu/torch_stable.html || echo ""
      shell: bash
    - run: action_env/bin/python3 ${GITHUB_ACTION_PATH}/run.py || action_env/Scripts/python.exe ${GITHUB_ACTION_PATH}/run.py || echo ""
      shell: bash
    - run: ls ${{ inputs.target_dir }}/MNIST/raw
      shell: bash
    - run: ls ${{ inputs.target_dir }}/MNIST/processed || echo ""
      shell: bash
