name: 'Download MNIST GitHub Action'
description: 'http://yann.lecun.com/exdb/mnist Dataset Mirror'

inputs:
  target_dir:
    description: 'Target dir, files will be copied to target_dir/MNIST/raw'
    required: true
    default: '.'

runs:
  using: 'composite'
  steps:
    # Create target path
    - run: mkdir -p ${{ inputs.target_dir }}/MNIST/raw
      shell: bash
    # Copy files to the target_dir/MNIST/raw
    - run: cp ${GITHUB_ACTION_PATH}/*.gz ${{ inputs.target_dir }}/MNIST/raw
      shell: bash
