name: 'Download MNIST GitHub Action'
description: 'http://yann.lecun.com/exdb/mnist Dataset Mirror'

inputs:
  target_dir:
    description: 'Target dir. Defaults: .'
    required: true
    default: '.'

runs:
  using: 'composite'
  steps:
    - run: python3 ${GITHUB_ACTION_PATH}/cp.py ${GITHUB_ACTION_PATH} ${{ inputs.target_dir }}/MNIST/raw || python.exe ${GITHUB_ACTION_PATH}/cp.py ${GITHUB_ACTION_PATH} ${{ inputs.target_dir }}/MNIST/raw || echo ""
      shell: bash

    - run: ls -R ${{ inputs.target_dir }}/MNIST
      shell: bash
