name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Run Action
        uses: ./
        with:
          target_dir: /tmp

      - name: Inspect Dir Content 
        run: ls -R /tmp/MNIST
